---
- name: Install Kubernetes common components on Master and Slave
  hosts: kubernetesmaster,kubernetesminion1,kubernetesminion2
  roles:
     - k8s_common

- name: Install Kubernetes Master
  hosts: kubernetesmaster
  roles:
     - k8s_master

- name: Install Kubernetes Minion
  hosts: kubernetesminion1,kubernetesminion2
  become: true
  roles:
     - k8s_minion    
