# Create a pod and expose port 8080
apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: midproj-pod
spec:
  containers:
    - image: ilanbowen/myflaskproj_img:latest
      name: myflaskproj_cont
      ports:
      - containerPort: 5000
        name: http
        protocol: TCP
#---
#apiVersion: v1
#kind: Service
#metadata:  
#  name: opsschool-service
#spec:
#  selector:    
#    app: opsschool
#  type: NodePort
#  ports:  
#  - name: http
#    port: 80
#    targetPort: 8080
#    nodePort: 30036
#    protocol: TCP
