---
- name: Docker - Install Docker common components on Master and Slave
  hosts: all
  roles:
     - docker_common

- name: Install Kubernetes common components on Master and Slave
  hosts: all
  roles:
     - k8s_common

- name: Install Kubernetes Master
  hosts: control1
  roles:
     - k8s_master

- name: Install Kubernetes Slave
  hosts: app
  roles:
     - k8s_minion    

- name: Jenkins - Install Jenkins Master
  hosts: control1
  become: true
  roles:
     - jenkins_master

- name: Jenkins - Create Jobs
  hosts: control1
  become: true
  roles:
     - jenkins_cli_create_clone_git_repo_job
     - jenkins_cli_create_build_docker_image_job
     - jenkins_cli_create_upload_docker_image_to_dockerhub_job
     - jenkins_cli_create_deploy_docker_app_in_k8s_job

- name: Jenkins - Build Jobs
  hosts: control1
  become: true
  roles:
     - jenkins_cli_build_clone_git_repo_job
     - jenkins_cli_build_build_docker_image_job
     - jenkins_cli_build_upload_docker_image_to_dockerhub_job
     - jenkins_cli_build_deploy_docker_app_in_k8s_job

- name: Consul - Install Agent on Server
  hosts: control1
  become: true
  roles:
     - consul_install_server

- name: Consul - Install Agent on Client
  hosts: app
  become: true
  roles:
     - consul_install_client