---
- name: Install K8S master services
  hosts: control
  tasks:
    - name: General | Load varibles
      include_vars:
        file: vars.yml

    - name: K8S | Install Master | Initialize K8S with kubeadm
      shell: kubeadm init --token={{ kubeadm_token }} --apiserver-advertise-address={{ k8s_master_ip }} --pod-network-cidr=10.10.0.0/16
      become: true
      become_method: sudo

    - name: K8S | Install Master | Create .kube directory
      file:
        path: /home/ubuntu/.kube"
        state: directory

    - name: K8S | Install Master | Copy admin.conf file to /.kube/config
      shell: "cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config"
      become: true
      become_method: sudo

    - name: K8S | Install Master | Change ownership on /.kube/config
      file:
        path: "/home/ubuntu/.kube/config"
        owner: ubuntu
        group: ubuntu
      become: true
      become_method: sudo

