---
- name: install wget
  apt:
    name: wget
    state: present

- name: install openjdk
  apt:
    name: openjdk-8-jre
    state: present

- name: Add Jenkins apt repository key.
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Add Jenkins apt repository.
  apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian binary/'
    state: present
    update_cache: true

- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: yes

- name: install jenkins
  apt:
    name: jenkins
    state: present

- name: start jenkins
  systemd:
    name: jenkins
    state: started

- name: enable jenkins
  systemd:
    name: jenkins
    enabled: true

- name: sleep for 30 seconds and continue with play
  wait_for: timeout=30
  delegate_to: localhost

- name: Disable Jenkins setup wizard
  lineinfile:
    dest=/etc/default/jenkins
    regexp=^JAVA_ARGS=
    line=JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
  become: true

- name: Create initialization scripts directory
  file: path=/var/lib/jenkins/init.groovy.d
        state=directory
        owner=jenkins
        group=jenkins
        mode=0775

- name: Add initialization script to setup basic security
  template: src=security.groovy.j2
            dest=/var/lib/jenkins/init.groovy.d/security.groovy

- name: restart jenkins
  service: name=jenkins state=restarted

- name: init password jenkin
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: print init password jenkins
  debug:
    var: result.stdout