---
- name: init password jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: Jenkins - Build BuildDockerImage Job
  shell: java -jar /opt/jenkins-cli.jar -s http://localhost:8080/ -auth admin:{{ result.stdout }} build BuildDockerImage
  become: yes
  become_method: sudo