---
- name: init password jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: Jenkins - Create Clone GitRepo Job
  shell: java -jar /opt/jenkins-cli.jar -s http://localhost:8080/ -auth admin:{{ result.stdout }} create-job CloneGitRepo < /home/ubuntu/midproject/Jenkins_Jobs/CloneGitRepo_Job.xml
  become: yes
  become_method: sudo