---
# tasks file for slave
- name: K8S | Install Minion | Join K8S with kubeadm
  shell: kubeadm join --token={{ kubeadm_token }} --discovery-token-unsafe-skip-ca-verification {{ k8s_master_ip }}:6443 
  become: yes
  become_method: sudo  