---
# tasks file for slave
- name: K8S | Install Minion | Join K8S with kubeadm
  shell: kubeadm join --token={{ kubeadm_token }} --discovery-token-unsafe-skip-ca-verification {{ hostvars[groups['kubernetesmaster'][0]]['ansible_eth0']['ipv4']['address'] }}:6443 
  become: yes
  become_method: sudo  

- name: K8S | Install Minion | Change permissions on /home/ubuntu/.kube to ubuntu:ubuntu
  file: 
    path: /home/ubuntu/.kube
    state: directory
    recurse: yes
    owner: ubuntu
    group: ubuntu

- name: K8S | Install Minion | Copy the contents of /home/ubuntu/.kube to /home/ubuntu
  shell: cp -r /home/ubuntu/.kube ~
  become: yes
  become_method: sudo  

- name: K8S | Install Minion | Change the ownership of ~/.kube to jenkins:jenkins
  file: 
    path: ~/.kube
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins  
  
- name: K8S | Install Minion | Make the script createpodandservice.sh executable
  file: 
    path: /home/ubuntu/midproject/Kubernetes/createpodandservice.sh
    mode: 777