---
# tasks file for slave
- name: K8S | Install Minion | Join K8S with kubeadm
  shell: kubeadm join --token={{ kubeadm_token }} --discovery-token-unsafe-skip-ca-verification {{ k8s_master_ip }}:6443 
  become: yes
  become_method: sudo  

- name: K8S | Install Minion | Change permissions on /home/ubuntu/.kube to ubuntu:ubuntu
  shell: chown -R ubuntu:ubuntu /home/ubuntu/.kube
  become: yes
  become_method: sudo  

- name: K8S | Install Minion | Copy the contents of /home/ubuntu/.kube to /home/ubuntu
  shell: cp -r /home/ubuntu/.kube ~
  become: yes
  become_method: sudo  

- name: K8S | Install Minion | Change the ownership of ~/.kube to jenkins:jenkins
  shell: chown -R jenkins:jenkins ~/.kube
  become: yes
  become_method: sudo
  
- name: K8S | Install Minion | Make the script createpodandservice.sh executable
  shell: chmod a+x /home/ubuntu/midproject/Kubernetes/createpodandservice.sh
  become: yes
  become_method: sudo