---
# tasks file for consul client install
- name: Consul | Install Server
  shell: /home/ubuntu/midproject/consul_client_install_config.sh
  become: yes
  become_method: sudo  

- name: Move k8ssvc-30001.json to /etc/consul.d/k8ssvc-30001.json
  command: mv /home/ubuntu/midproject/k8ssvc-30001.json /etc/consul.d/k8ssvc-30001.json
  become: yes
  become_method: sudo

- name: Sleep 30
  command: sleep 30
  become: yes
  become_method: sudo  
  
- name: Restart Consul
  command: systemctl reload consul
  become: yes
  become_method: sudo  
     
      
   